### ISSUE TITLE
Question: How to add a 2D fixed joint

### ISSUE THREAD

**Issue by ManuelZ** [jgerstmayr/EXUDYN#12]
Hi, 

How can I add a 2D joint that restricts all three degrees of freedom? Should I use `GenericJoint`?

**Comment by jgerstmayr** [comment]
For a RigidBody2D you can:
- use 3  CoordinateConstraint objects to constrain displacement and rotation, OR
- use a GenericJoint and fix 2 displacements and rotation around Z-axis (but leave other axes free), OR
- use a GroundObject, as your body is not moving and it is probably not needed.
To prescribe a motion, you can use user functions either in the CoordinateConstraint objects or use GenericJoint with an offsetUserFunction

**Comment by ManuelZ** [comment]
Great, thanks, I did it with a GenericJoint.
