### ISSUE TITLE
Question: LoadForceVector-Function (UserFunction)

### ISSUE THREAD

**Issue by csas8682** [jgerstmayr/EXUDYN#14]
Hello, 

I have a two questions regarding the __LoadForceVector-Function__: 

- If I want to use the _loadVectorUserFunction_ is it necessary, or rather does it make a difference, if I pass a _loadVector_ as argument when I use a userfunction anyway? As far as I understand the _loadVectorUserFunction_ returns the _loadVector_ and therefore updates the _loadVector_ in every time step?

I am asking, because I tried to leave the _loadVector_ empty, the simulation and calculation worked, but no Load was displayed on my mbs. The load was certainly applied, because it was still moving...

- In the _VisualizationSettings_ is it possible to update the _loadVector_. I am askings, because I try to use a time- (or rather position-) depending _loadVector_, and wonder if I could see it in the visualzation if it gets updated correctly. 

Thank you very much in advance 🙏🏼I hope my questions are clear! 

Kind regards!

**Comment by jgerstmayr** [comment]
Python user function can currently not be called within the visualization; therefore, the loadVector cannot be updated during drawing. Add a sensor, which shows the currently computed value by the user function. If you want to update the value during visualization, use a preStepUserFunction (which will just update during simulation), or use a graphicsDataUserFunction - e.g. on a GroundObject - which can draw globally and synchronized with visualization states.
