### ISSUE TITLE
An error in "geometricallyExactBeam3Dtest.py"

### ISSUE THREAD

**Issue by Jiang-Cui** [jgerstmayr/EXUDYN#18]
Dear professor,

I run "geometricallyExactBeam3Dtest.py", but an error occurs as follows:

>File "main\pythonDev\TestModels\geometricallyExactBeam3Dtest.py", line 55, in <module>
>    sectionData = exu.BeamSection()
>AttributeError: module 'exudyn' has no attribute 'BeamSection'

Could you help me solve the question? Thank you!

**Comment by jgerstmayr** [comment]
First I assume, that you are not using the latest version of exudyn, which you can get with:
pip install exudyn --pre

However, as said at the very beginning of ObjectBeamGeometricallyExact3D in theDoc.pdf:
"OBJECT UNDER CONSTRUCTION"

It will take some weeks from now to be completed.

**Comment by Jiang-Cui** [comment]
Thank you, Professor Gerstmayr! It can work!
