### ISSUE TITLE
About algorithm Principle

### ISSUE THREAD

**Issue by yumianhuli2** [jgerstmayr/EXUDYN#19]
Hello!Dear EXUDYN Team!
I have the following questions：
 1 Is this flex-multibody dynamics encoded based on Newton Euler recursive formula or Lagrange formula + constraint or both?
 2 If it's Newton-Euler where is the core recursive formula in the file? If it's Lagrange, where are the core documents
3  I see the finite element display in the engine piston connecting rod in the picture introduced, is this package similar to Recurdyn MBFD(multibody-flex with FEA) calculation formula at the same time?
Thank you very much！

**Comment by jgerstmayr** [comment]
1) The formulation in general is using redundant coordinates with constraints. Equations for objects are derived in various ways, so there is no particular Newton-Euler or Lagrange, except for the Rigid body; this is described in theDoc.pdf at the according objects.
2) The recursive formalism is only available in the KinematicTree, see KinematicTree.cpp
3) I to no know Recurdyn in depth, but Exudyn uses no approximation of inertia and directly import finite element stiffness and mass matrices. It has a rich interface to NGsolve (ngsolve.org), but also to Abaqus and Ansys
You are welcome!

**Comment by yumianhuli2** [comment]
> 

Thank you！
