### ISSUE TITLE
Question: Is there any 2D mobile robot example?

### ISSUE THREAD

**Issue by ManuelZ** [jgerstmayr/EXUDYN#20]
Hi, 

1) I'd like to know if there is any example for a setup like this please:

![image](https://user-images.githubusercontent.com/115771/182003609-469cbf4d-aca8-4fb2-8162-16f38588ead6.png)

The `leggedRobot.py` example seems to be the most similar.

2) If I manage to create one, how could I create an undulating floor?

**Comment by jgerstmayr** [comment]
There is no 2D robot yet. For 2D kinematic trees, see TestModels/kinematicTreeAndMBStest.py.
Regarding mobile robots, you can use TestModels/carRollingDiscTest.py for the wheel (even this is 3D) and add an arm, similar to any 2D chain as in Examples/testGymDoublePendulumEnv.py.
A 3D mobile platform exists as TestModels/mecanumWheelRollingDiscTest.py.

For a arbitrary floor, you can use the GeneralContact module (though, this is not 100% tested, but it should work for this case). There, you create wheels as rigid particles.
