### ISSUE TITLE
SolutionViewer

### ISSUE THREAD

**Issue by MichaelUIBK** [jgerstmayr/EXUDYN#28]
When loading solution from multiple computed static problems the SolutionViewer does not correctly load the solution.
There are several steps shown where there is no displacement.

**Comment by jgerstmayr** [comment]
LoadSolution() does currently not work with comments in between multiple steps. 
For workaround set:
    simulationSettings.solutionSettings.writeFileFooter = False
and after first SolveStatic() or SolveDynamic(), set:
    simulationSettings.solutionSettings.writeFileHeader = False
This will create consistent solution files.

**Comment by jgerstmayr** [comment]
with version 1.4.60.dev1 this issue is fully resolved; the SolutionViewer now accepts any comment lines in solution; writing of initial values can be turned off consistently by according solutionSettings.writeInitialValues flag.
