### ISSUE TITLE
Mistake in Page 244

### ISSUE THREAD

**Issue by LukasNeurauter** [jgerstmayr/EXUDYN#29]
The description for RotationMatrixY and Z on page 244 explains that it is a rotation around the X-axis (axis 0). But it should be a rotation around Y or Z instead.

![grafik](https://user-images.githubusercontent.com/122445878/211786664-84917204-36e2-48c9-8554-5dc19be8ee7d.png)

**Comment by jgerstmayr** [comment]
Thanks for the hint, that are a lot copy-paste errors. Will be fixed in the next update (version 1.5.53).
