### ISSUE TITLE
Pause a simulation during runtime 

### ISSUE THREAD

**Issue by slyandsmart** [jgerstmayr/EXUDYN#30]
It would be nice to have a way to pause the simulation. I would suggest to use the space bar (as in multiple other programs). 
Whereby one hit on the spacebar pause and a second hit would resume the simulation.

**Comment by jgerstmayr** [comment]
A pause is possible by pressing the 'V' (to open the visualization dialog)  or 'X' to show the command dialog. During this break, you can rotate/zoom/translage the model.
Break with Space bar may be included in next update.
