### ISSUE TITLE
The issue of the ngsolve installation 

### ISSUE THREAD

**Issue by Jiang-Cui** [jgerstmayr/EXUDYN#31]
Dear Professor Johannes Gerstmayr, 

I found that the python main files requiring the ngsolve such as NGsolveCraigBampton.py could not be run. The following error occurs.
>  File "D:\EXUDYN\main\pythonDev\Examples\NGsolveCraigBampton.py", line 71, in <module>
>  import ngsolve as ngs

>  File "D:\Program Files\ngsolve-v6.2.2203\lib\site-packages\ngsolve\__init__.py", line 19, in <module>
>  import netgen

> File "D:\Program Files\ngsolve-v6.2.2203\lib\site-packages\netgen\__init__.py", line 17, in <module>
> from . import libngpy

> ImportError: DLL load failed

I try to reinstall the ngsolve using "pip install ngsolve", the following error shows.
> ERROR: Could not find a version that satisfies the requirement ngsolve (from versions: none)
> ERROR: No matching distribution found for ngsolve

Could you help me solve this issue?

Thank you!

**Comment by jgerstmayr** [comment]
I need more information on Python version and platform (Windows, ...).
On windows, ngsolve works best with Python 3.10. 
There are issues with Python 3.8. But this is not at my disposal, you could write this to ngsolve developers ... 
I also saw that it helps, if you try different ngsolve versions, e.g., install with "pip install ngsolve --pre"

**Comment by Jiang-Cui** [comment]
Many thanks for you, Professor!

The platform is windows. The python version is 3.10.3 using the code "python --version". I also install the python 3.7 in the platform. 

"pip install ngsolve --pre" cannot work. The the following error still shows.
> ERROR: Could not find a version that satisfies the requirement ngsolve (from versions: none)
> ERROR: No matching distribution found for ngsolve

**Comment by jgerstmayr** [comment]
I am using Python 3.10.8 within an environment. Maybe you need to update your Python version - it seems to be that you are using a quite old one.
If doing "pip install ngsolve", I currently get version NGsolve-6.2.2301. Then I can run python NGsolveCMStutorial.py . I do everything within a Python environment, which may behave different from a direct Python installation.

**Comment by Jiang-Cui** [comment]
Professor, I have built a new environment including python 3.10 in Anoconda. The "pip install ngsolve" can work, and NGsolveCMStutorial.py can run in Spyder.Thank you very much! 

However, another issue occurs! The main *.py file cannot be debugged through "main_sln_Template.sln". The error "The pdb file cannont be found" shows in the VS2017. Could you help me solve the new issue?
