### ISSUE TITLE
Are vibration due to inertia & acceleration simulated?

### ISSUE THREAD

**Issue by ax-anoop** [jgerstmayr/EXUDYN#32]
Looking for a simulator that I can use to learn about input shaping, would this simulate vibrations accurately?

**Comment by jgerstmayr** [comment]
This is a (flexible) multibody dynamics simulator. Setting integration parameters appropriately, you can achieve any accuracy that you need. Input profiles can be described with loads and Python user functions. It depends, what kind of system you intend to solve. If you have no constraints, you can use explicit integrators with very high accuracy.
