### ISSUE TITLE
Exudyn installation on Ubuntu2004

### ISSUE THREAD

**Issue by qkhadim22** [jgerstmayr/EXUDYN#40]
I followed installation guide (https://exudyn.readthedocs.io/en/latest/docs/RST/InstallationInstructions.html#build-and-install-exudyn-under-ubuntu) for installing Exudyn on Ubuntu2004 with Python3.10.  After the installation, when I run python3 pythonDev/Examples/rigid3Dexample.py. I get the following error :  

X11: Failed to open display :0.0 terminate called without an active exception Aborted.

1. How to fix this error?
2. The installation of Exudyn automatically installs 3.8. Even though, I have completely removed 3.8 and upgraded Ubuntu2004 to 3.10. Could you please elaborate this?

**Comment by jgerstmayr** [comment]
1) Seems that you have problems with X11, not related with Exudyn. Try starting xcalc, nedit or any other X11 application. I assume that you get the same error.

2) Ubuntu 20.04: seems that you have problems with your conda environment (which is not related to Exudyn). run python3 on your machine and see if you get a Python 3.8 or 3.10 console. If you remove Python3.8 completely, you cannot compile for Python 3.8, right?

**Comment by qkhadim22** [comment]
Thanks for your quick response. 

1. Your are right. The first problem is related to X11 and not with Exudyn. The easiest way to solve this problem is to update WSL by following (https://askubuntu.com/questions/1449804/wsl-when-i-try-to-use-gui-package-get-error-cant-open-display).                                                                                                                                                                     

2. Ubuntu2004 comes with Python 3.8 installed by default. Some functionalities of Ubuntu2004 depend upon Python3.8. So, if Python3.8 is not removed properly then it will-reinstall automatically.
