### ISSUE TITLE
Wrong object type for Prismatic joint

### ISSUE THREAD

**Issue by ManuelZ** [jgerstmayr/EXUDYN#41]
The following error made me believe that my problems were related to a Revolute joint, but after looking for `object 17`, I found out they are related to a Prismatic Joint.

```
Potential object number(s) causing linear solver to fail: [17]
    object 17, name='object17', type=JointRevolute
```

Such joint is being created through `AddPrismaticJoint`, hence, through `ObjectJointPrismaticX`.

I think the problem comes from here:
https://github.com/jgerstmayr/EXUDYN/blob/866099d2dd829f543171721ab473a73f942bae9d/main/src/Autogenerated/MainObjectJointPrismaticX.h#L101

The following are related files with a similar "JointRevolute" string present:
MainObjectJointRevolute.h
MainObjectJointRevoluteZ.h
MainObjectJointPrismatic.h

**Comment by jgerstmayr** [comment]
Resolved with current update V1. 6.57
