### ISSUE TITLE
Error in ImportFromAbaqusInputFile

### ISSUE THREAD

**Issue by qkhadim22** [jgerstmayr/EXUDYN#43]
We are using Abaqus2020 to create .inp file. The mesh is created using the Exudyn guidelines. However, we are receiving the error below:

raise ValueError("ImportFromAbaqusInputFile: element type '"+elementTypeName+"' can not yet be imported")
ValueError: ImportFromAbaqusInputFile: element type 'C3D10' can not yet be imported.

But, we can use Hex8, Hex20, Tet4 and Tet10 (C3D4, C3D8, C3D10, C3D20) elements for mesh according to the documentation.

**Comment by jgerstmayr** [comment]
Try to update to the most current version 1.6.65.dev1. It now includes all mentioned elements including C3D4, C3D8, C3D8R, C3D10, C3D20, C3D20R.
