### ISSUE TITLE
Doc references AccelerationLocal but is not present in OutputVariableType

### ISSUE THREAD

**Issue by ManuelZ** [jgerstmayr/EXUDYN#46]
I'm seeing references to `AccelerationLocal` in the docs (e.g. page 373) but I can't find it in `exudyn.OutputVariableType` :

```
import exudyn

for x in dir(exudyn.OutputVariableType):
    if not x.startswith("__"): print(x)


Acceleration
AngularAcceleration
AngularVelocity
AngularVelocityLocal
ConstraintEquation
Coordinates
Coordinates_t
Coordinates_tt
CurvatureLocal
Director1
Director2
Director3
Displacement
DisplacementLocal
Distance
Force
ForceLocal
Position
Rotation
RotationMatrix
SlidingCoordinate
StrainLocal
StressLocal
Torque
TorqueLocal
Velocity
VelocityLocal
_None
name
value
```

BTW 1: in page 78 of `theDoc.pdf`, there seems to be an unneeded word "compileAll" at the end of the page.

**Comment by jgerstmayr** [comment]
Thanks!
The parameters AccelerationLocal, AngularAccelerationLocal are missing in pybind interface.
Will be fixed with Issue 1553 in version 1.6.93
In fact you can use the value 128 instead of AccelerationLocal for the meantime. It is one bitshift higher than Acceleration.
