### ISSUE TITLE
graphicsDataUserFunction in SolutionViewer

### ISSUE THREAD

**Issue by peter-manzl** [jgerstmayr/EXUDYN#51]
python 3.10.9
exudyn Version 1.6.176.dev1

I am using the graphicsDataUserFunction to draw the spatial trajectory a point from sensor data. It works while simulating and also in the solutionViewer. But when activating the recordAnimation the graphicsDataUserFunction  is no longer called. 

Here you can see the blue Trajectory correctly displayed. 
![workingExample](https://github.com/jgerstmayr/EXUDYN/assets/57989126/ba9b4dc6-f824-4e35-a907-893889ca282d)

When pressing "record animation" it vanishes. The same thing happens when the "Stop" button is pressed. 
![notWorkingExample](https://github.com/jgerstmayr/EXUDYN/assets/57989126/e677ae9f-18b1-44a0-8ea4-8b544f86ca36)

When adding a print statement into the graphicsDataUserFunction I found that the function is not called at all.

**Comment by jgerstmayr** [comment]
This is, unfortunately, a bug. Is fixed in version 1.6.182.
Recording also does not work with the single-threaded renderer, which will be fixed in this version as well.
