### ISSUE TITLE
A data problem in FEM.py

### ISSUE THREAD

**Issue by Jiang-Cui** [jgerstmayr/EXUDYN#55]
Dear Prof. Gerstmayr,

I have successfully install Exudyn in VS2017 and Python 3.7 in both Windows 10 and 11 with your help. 

When I debug NGsolveCraigBampton.py in VS2017, a problem occurs as shown

![2881c398ef6bebd8e14698c4f512f3c](https://github.com/jgerstmayr/EXUDYN/assets/84257410/eae79c5a-4cb0-4edd-b67b-3140822db1ff)

I use the old-version FEM.py to replace the latest FEM.py, this problem is solved. Dose the latest FEM.py not suitable to the netgenBrick.npy and netgenHinge.npy generated by ngsolve?

**Comment by jgerstmayr** [comment]
As stated in the error message, if loading an old .npy file, you should set forceVersion=0. Alternatively, you can save the .npy file in the new format. Future versions of .npy files include a version and thus will not have this problem.
