### ISSUE TITLE
Inconsistency: Output variable type "AccelerationLocal" mentioned in "theDoc" but not working for "RigidBody2D"

### ISSUE THREAD

**Issue by a12er** [jgerstmayr/EXUDYN#57]
sSliderAccLocal=mbs.AddSensor(SensorBody(outputVariableType=exu.OutputVariableType.AccelerationLocal,bodyNumber=oMass, storeInternal=False, writeToFile=True, fileName='sSliderAccLocal.txt' ))

AttributeError: type object 'exudyn.exudynCPP.OutputVariableType' has no attribute 'AccelerationLocal'

**Comment by jgerstmayr** [comment]
This should be a version problem. You have to provide version number when writing issues.
Try updating Exudyn, then this should be resolved. 
See issue 1.6.93: https://exudyn.readthedocs.io/en/latest/docs/RST/trackerlog.html
Update to 1.7.0 and this should be resolved.
