### ISSUE TITLE
reevingSystemOpen

### ISSUE THREAD

**Issue by killes** [jgerstmayr/EXUDYN#59]
In this video we can see a pulley system:
https://www.youtube.com/watch?v=L1-QxVvH3bc

Is the source available somewhere? I couldn't find it. Thanks!

**Comment by jgerstmayr** [comment]
you are right, it is missing.

It is now under Examples/reevingSystemOpen.py

It uses an old version of the motion planning, but you could use the new functionality of the robotics module. Furthermore, solver settings are not ideal, as it switches to small time steps around 4 seconds ... this could be improved easily.

**Comment by killes** [comment]
Thank you!
