### ISSUE TITLE
Type hints in GetSensorValues

### ISSUE THREAD

**Issue by ManuelZ** [jgerstmayr/EXUDYN#61]
The type hints in [GetSensorValues](https://github.com/jgerstmayr/EXUDYN/blob/05de550b733ae2a11f0d4db4bb17b88725e95b71/main/pythonDev/exudyn/__init__.pyi#L1499) say that the second argument (`configuration`) is required, but it really isn't, [as it has a default value](https://github.com/jgerstmayr/EXUDYN/blob/05de550b733ae2a11f0d4db4bb17b88725e95b71/main/src/Autogenerated/pybind_manual_classes.h#L263) of `ConfigurationType::Current`.

**Comment by jgerstmayr** [comment]
you are totally right. This happened due to automatic conversion of interfaces to .pyi files.
This is fixed in version 1.8.14.

Thanks a lot!
