### ISSUE TITLE
ValueError when using graphics.FromSTLfile

### ISSUE THREAD

**Issue by ManuelZ** [jgerstmayr/EXUDYN#73]
```
Traceback (most recent call last):
    ...
    graphics.FromSTLfile(
  File "C:\...\Lib\site-packages\exudyn\graphics.py", line 1426, in FromSTLfile
    if A == []: A=np.eye(3)
       ^^^^^^^
ValueError: operands could not be broadcast together with shapes (3,3) (0,)
```

This happens when calling `FromSTLfile` with `Aoff=RotationMatrixX(theta)`, because the `RotationMatrix` functions return a Numpy array and the `==` operation is making Numpy compare the shapes of `Aoff` and `[]`, but the [broadcasting rules'](https://numpy.org/doc/stable/user/basics.broadcasting.html#general-broadcasting-rules) conditions are not met, hence the ValueError.

[Link](https://github.com/jgerstmayr/EXUDYN/blob/b1bc20dc7ffb395281d02551be3b234fd13fc6d1/main/pythonDev/exudyn/graphics.py#L1426)

Could a potential solution be to replace `A == []` and `p == []` with `len(A) == 0` and `len(p) == 0`? That worked for me.

Exudyn 1.8.52.dev1.

**Comment by jgerstmayr** [comment]
You are right! 
will be changed in version 1.8.55 to:
```
    if not IsEmptyList(p) or not IsEmptyList(A):
        if IsEmptyList(p): p=[0,0,0]
        if IsEmptyList(A): A=np.eye(3)
        HT = HomogeneousTransformation(A, p)
        
        data.transform(HT)
```
with the new function:
```
def IsEmptyList(x):
    if isinstance(x, list) or isinstance(x, np.ndarray):
        return len(x) == 0
    return False 

```
**you can change your file locally in between or convert numpy arrays to lists of lists**!
I will also check other places as this pops up now and then.
