### ISSUE TITLE
GraphicsData: Line invalid syntax

### ISSUE THREAD

**Issue by MichaelUIBK** [jgerstmayr/EXUDYN#80]
In the example of **GraphicsData: Line** the following code is given:

#rectangle with side length 1:
graphicsData = {'type':'Line',
                'color': [1,0,0,1], #red
                'data': data=[0,0,0,
                              1,0,0,
                              1,1,0,
                              0,1,0,
                              0,0,0]}

vGround=VObjectGround(graphicsData=[graphicsData])
oGround=mbs.AddObject(ObjectGround(referencePosition= [0,0,0],
                                 visualization=vGround))

This code gives a SyntaxError: invalid syntax. I suppose in "... 'data': data=[0,0,0, ..." the "data=" should be removed.

**Comment by jgerstmayr** [comment]
fixed in new version!
