### ISSUE TITLE
Visualization of a harmonic load in the mbs.SolutionViewer()

### ISSUE THREAD

**Issue by MichaelUIBK** [jgerstmayr/EXUDYN#82]
In the example nMassOscillator.py, a harmonic load used as an excitation force in the userFunction is not visualized in the solutionViewer correctly; instead, the force is shown to be static.

**Comment by jgerstmayr** [comment]
Will be available in version 1.9.1, with new  visualizationSettings.loads.drawWithUserFunction - see description there!
