### ISSUE TITLE
Exudyn cannot be updated to Version 1.9.0

### ISSUE THREAD

**Issue by bermar98** [jgerstmayr/EXUDYN#83]
Exudyn cannot be updated from version 1.7.0 to version 1.9.0 using the command "pip install exudyn --pre -U".
The following message is returned:
Requirement already up-to-date: exudyn in c:\users\marcu\anaconda3\lib\site-packages (1.7.0)
Requirement already satisfied, skipping upgrade: numpy in c:\users\marcu\anaconda3\lib\site-packages (from exudyn) (1.21.6)

PC: Windows with Intel Core i7
Application: Spyder with Python 3.7

In version 1.7.0, an error message is returned when using "import exudyn.graphics as graphics".

**Comment by jgerstmayr** [comment]
It seems that you do not have access to the pypi repo or some similar issue.
In any case, deinstallation and installation should give you the newest release. For the release, you do not need the "--pre" flag.

It may also be the case that you have some crashed site-packages directory, or you have Exudyn still running within some Python environment, which hinders exudyn to be updates.
