### ISSUE TITLE
Error in 'MatrixContainer::SetWithSparseMatrixCSR' in function CreateNonlinearFEMObjectGenericODE2NGsolve(); Exudyn Version 1.9.0

### ISSUE THREAD

**Issue by stehol01** [jgerstmayr/EXUDYN#87]
I would like to run a nonlinear static or dynamic FEM simulation using the ngsolve interface of exudyn. In exudyn version 1.8.52.dev1, the simulation model runs without errors. However, in exudyn version 1.9.0, it seems that there is an issue with 'MatrixContainer::SetWithSparseMatrixCSR' in function CreateNonlinearFEMObjectGenericODE2NGsolve(). Thanks for the help.

**Comment by jgerstmayr** [comment]
CreateNonlinearFEMObjectGenericODE2NGsolve does not work due to change in internal FEM stiffness and mass matrices. You can temporarily change to the following lines:
        Mcsr = exu.MatrixContainer()
        Mcsr.SetWithSparseMatrix(fem.GetMassMatrix(), useDenseMatrix=False)
        Kcsr = exu.MatrixContainer()
        Kcsr.SetWithDenseMatrix(fem.GetStiffnessMatrix(), useDenseMatrix=False)

Will be fixed in version 1.9.50 !
