### ISSUE TITLE
Suggestion on location of binaries

### ISSUE THREAD

**Issue by ManuelZ** [jgerstmayr/EXUDYN#9]
Hi, I'd suggest to put the compiled binaries into the "Releases" section of Github and not in the repository along the code, because a user git-cloning the repository ends up downloading unneeded binaries otherwise.

As a side note, I found out about Hotint some months ago, and thought, "Wow, this is a great program, how could would it be if it would be updated". And then I found Exudyn!

**Comment by jgerstmayr** [comment]
binaries are now on pypi.org
use pip install exudyn to install from binaries on Windows (and some linux/MacOS versions)
